version: "3.8"

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gather-react
    ports:
      - "3000:3000"

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   depends_on:
  #     - react
  #   networks:
  #     - app-network

networks:
  default:
    name: gather-network
