name: Front Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions: write-all

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    name: react build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout Github Action
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 원하는 Node.js 버전을 지정하세요.

      - name: Install dependencies
        run: npm install

      - name: react build
        run: npm run build

      - name: Make directory
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/togather

      - name: Transfer Build Folder
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            dist
          target: "/home/ubuntu/togather"

      - name: Using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/togather
            sudo docker compose down
            sudo docker compose up --build -d
